<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by lupdate-c. To update this file, run the 'lupdate-c' command below. -->
<!-- lupdate-c -i "../main.c" -o "mdoutliner_en.ts" -l "en_US" -->
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>Main</name>
    <message>
        <location filename="main.c" line="111"/>
        <source>&amp;File</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.c" line="115"/>
        <source>&amp;New Tab</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.c" line="119"/>
        <source>Ctrl+N</source>
        <comment>New tab</comment>
        <translation></translation>
    </message>
    <message>
        <location filename="main.c" line="125"/>
        <source>&amp;Open...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.c" line="129"/>
        <source>Ctrl+O</source>
        <comment>Open a file</comment>
        <translation></translation>
    </message>
    <message>
        <location filename="main.c" line="135"/>
        <source>&amp;Exit</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.c" line="139"/>
        <source>Ctrl+Q</source>
        <comment>Quit</comment>
        <translation></translation>
    </message>
    <message>
        <location filename="main.c" line="145"/>
        <source>&amp;Options</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.c" line="149"/>
        <source>&amp;Language</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.c" line="153"/>
        <source>&amp;English</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.c" line="157"/>
        <source>&amp;French</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.c" line="161"/>
        <source>&amp;Spanish</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.c" line="165"/>
        <source>&amp;Help</source>
        <translation></translation>
    </message>
    <message>
        <location filename="main.c" line="169"/>
        <source>&amp;About Qt</source>
        <translation></translation>
    </message>
</context>
</TS>
